name: Continuous Deploy
on:
  push:
    branches:
      - 'main'
env:
  DOCKER_TAG: ${{ github.sha }}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}

jobs:
  ci:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{env.DOCKER_USER}}
        password: ${{env.DOCKER_TOKEN}}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ${{env.DOCKER_USER}}/charpg:${{ env.DOCKER_TAG }}
        push: true

  provision:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'mazzonixd/aws-ec2'

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     # terraform_version: 1.1.7
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check

      # - name: Terraform Init
      #   id: init
      #   run: terraform init

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color
      
      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color
      #   continue-on-error: true
      
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve

  cd:    
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - name: Create compose on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: "ubuntu"
          envs: DOCKER_TAG, DOCKER_USER
          script: |
            mkdir -p ~/charpg
            cat << EOF > ~/charpg/docker-compose.yml
            version: '3.9'
            services:
              charpg:
                image: ${DOCKER_USER}/charpg:${DOCKER_TAG}
                container_name: charpg
                hostname: charpg
                ports:
                  - '8080:8080'
              db:
                image: postgres
                container_name: charpgdb
                hostname: charpgdb
                environment:
                  - POSTGRES_DB=charpgdb
                  - POSTGRES_USERNAME=postgres
                  - POSTGRES_PASSWORD=postgres
                volumes:
                  - .:/var/lib/postgres/data

            EOF

      - name: Create compose on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: "ubuntu"
          script: |
            docker-compose -f ~/charpg/docker-compose.yml up -d --force-recreate --remove-orphans
