on:
  push:
    branches:
      -main
name: Enviando o Docker desse projeto
jobs:
  container:
    name: Container
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: github.event_name == 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      if: github.event_name == 'pull_request'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker-compose
        tags: ${{secrets.DOCKERHUB_USERNAME}}/charpg